advcbv/advcbv/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$',views.index),
    url(r'^$',views.IndexView.as_view()),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app')),

]

advcbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app_1'
urlpatterns=[
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailedView.as_view(),name="detail"),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name="update"),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name="delete"),

]

advcbv/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class School(models.Model):
    name=models.CharField(max_length=256)
    principal=models.CharField(max_length=256)
    location=models.CharField(max_length=256)
    def __str__(self):
        return self.name
    #used for entering name to model through webpage
    #This will redirect to http://127.0.0.1:8000/basic_app/6/ school detail page
    def get_absolute_url(self):
        return reverse("basic_app_1:detail", kwargs={'pk':self.pk})

class Student(models.Model):
    name=models.CharField(max_length=256)
    age=models.PositiveIntegerField()
    school=models.ForeignKey(School,related_name='students')

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,
                                DetailView,CreateView,UpdateView,
                                DeleteView)

from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from . import models

class IndexView(TemplateView):
    template_name='basic_app/index.html'
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context={'insert_me':'Hello!!'}
        return context

class SchoolListView(ListView):

    model=models.School
    template_name='basic_app_1/school_list.html'
    context_object_name='schools'
    #returns name school_list automatically


class SchoolDetailedView(DetailView):
    context_object_name="school_detail"
    model=models.School
    template_name='basic_app_1/school_detail.html'

class SchoolCreateView(CreateView):
    template_name="basic_app_1/school_form.html"
    fields = ('name','principal','location')
    model=models.School

class SchoolUpdateView(UpdateView):
    fields=('name','principal')
    model=models.School
    template_name='basic_app_1/school_form.html'
class SchoolDeleteView(DeleteView):
    model=models.School
    success_url=reverse_lazy("basic_app_1:list")
    template_name='basic_app_1/school_confirm_delete.html'

advcbv/basic_app/templates/basic_app_1/base_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app_1:list' %}">School</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
        <!-- <li><a href="#"></li> -->
      </ul>

    </nav>
  </body>

  <div class="container">
    {% block body_block%}

    {% endblock %}
  </div>
</html>

advcbv/basic_app/templates/basic_app_1/school_confirm_delete.html
{% extends "basic_app_1/base_app_base.html" %}
{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form  method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basic_app_1:detail' pk=school.pk %}">Cancel</a>

</form>
{% endblock %}

advcbv/basic_app/templates/basic_app_1/school_detail.html
{% extends "basic_app_1/base_app_base.html" %}

{% block body_block %}
<div class="container">
  <h1>Welcome to the school detail page</h1>
  <h2>School details:</h2>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.location}}</p>
  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
  <p>{{student.name}} who is {{student.age}}</p>
  {% endfor %}
</div>
<div class="container">
  <p><a class="btn btn-warning" href="{% url 'basic_app_1:update' pk=school_detail.pk %}">Update</a></p>

</div>
{% endblock %}

advcbv/basic_app/templates/basic_app_1/school_form.html
{% extends "basic_app_1/base_app_base.html" %}
{% block body_block%}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>
  <form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" name="" value="Submit">

  </form>
{% endblock %}

advcbv/basic_app/templates/basic_app_1/school_list.html
{% extends "basic_app_1/base_app_base.html" %}
{% block body_block%}
<h1>List of all Schools</h1>
<ol>
  {% for school in schools %}
  <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>

  {%endfor%}
</ol>

{%endblock%}

advcbv/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">


    {% block body_block %}

    {% endblock %}
    </div>
  </body>
</html>

advcbv/templates/basic_app/index.html
{% extends "basic_app/base.html"%}
{% block body_block %}
  <h1>Homepage</h1>
  {{insert_me}}
{% endblock %}